# Generated by Django 4.2.6 on 2023-11-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reversegeocodecache',
            name='uber_h3_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
