# Generated by Django 4.2.6 on 2023-11-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0002_reversegeocodecache_uber_h3_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='placescache',
            name='uber_h3_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
