# Generated by Django 4.2.6 on 2023-11-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0003_placescache_uber_h3_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePlacesCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_longitude', models.FloatField()),
                ('user_latitude', models.FloatField()),
                ('h3_id', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('plus_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
