# Generated by Django 4.1.7 on 2023-12-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0004_googleplacescache'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlacesCache',
        ),
        migrations.DeleteModel(
            name='ReverseGeocodeCache',
        ),
    ]
