# Generated by Django 4.1.7 on 2023-12-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0005_delete_placescache_delete_reversegeocodecache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleplacescache',
            name='h3_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='googleplacescache',
            name='user_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googleplacescache',
            name='user_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
