# Generated by Django 4.1.7 on 2023-12-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0006_alter_googleplacescache_h3_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleplacescache',
            name='source',
            field=models.CharField(choices=[('places', 'Places'), ('reverse_geocode', 'ReverseGeocode')], default='places', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='googleplacescache',
            name='h3_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='googleplacescache',
            name='place_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='googleplacescache',
            unique_together={('h3_id', 'place_id')},
        ),
    ]
