# Generated by Django 4.1.7 on 2023-12-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0007_googleplacescache_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleplacescache',
            name='h3_id',
            field=models.CharField(max_length=255),
        ),
    ]
