# Generated by Django 4.1.7 on 2023-12-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0008_alter_googleplacescache_h3_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleplacescache',
            name='h3_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='googleplacescache',
            name='place_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
